Added 12 systems
CkauNui/ckau-book pull request #7
Opened 2021-02-07 15:31 UTC by Lendersmark

Added the following systems in Colorful:

Amiga 1200
Commodore Vic 20
Commodore 16
Commodore Plus 4
Commodore 128
Sam Coupe
Ti-99
Sinclair ZX-81
Nintendo Famicom
Nintendo Super Famicom
SNES MSU-1
Sufami Turbo

Cloned some layouts and anim pngs for european system names (such as megacd instead of segacd)

2021-02-08 00:03 UTC, QuaiGoner commented
Is there a way to add Dendy in place of nes, and Sega mega drive 2 ? (

2021-02-08 03:20 UTC, CkauNui commented
**Lendersmark**, send me psd for new systems pls (in discord or gmail)

2021-02-08 09:36 UTC, Lendersmark commented
> **Lendersmark**, send me psd for new systems pls (in discord or gmail or google drive)
> thx

Sure, could you please give me your email address? or discord channel?

2021-02-08 18:32 UTC, CkauNui commented
> > **Lendersmark**, send me psd for new systems pls (in discord or gmail or google drive)
> > thx
> 
> Sure, could you please give me your email address? or discord channel?

ckau48@gmail.com

2021-05-03 13:20 UTC, mathsensey commented
Hello,
Is it possible to choose the video (s) that appear randomly for each system?

For example, when I'm on the SNES system, I would like only the Super Mario World video to show.

thank you in advance

2021-05-03 13:49 UTC, CkauNui commented
> Hello,
> Is it possible to choose the video (s) that appear randomly for each system?
> 
> For example, when I'm on the SNES system, I would like only the Super Mario World video to show.
> 
> thank you in advance

Yes, put ur mario video in "_inc\anim\video" and name "snes.mp4"

2021-05-03 13:56 UTC, mathsensey commented
And it will appear in the TV on the SNES system view? Ok great, I will test this

2022-04-02 12:29 UTC, g-spawnPL commented
Hello
I am sending my translation and descriptions in Polish along with graphics for batocera v33 and some of v34 systems. some of them may need improvement because I am not the best in making graphics
[layouts.zip](https://github.com/CkauNui/ckau-book/files/8402478/layouts.zip)
[logos.zip](https://github.com/CkauNui/ckau-book/files/8402479/logos.zip)
![adam](https://user-images.githubusercontent.com/87877685/161383214-a0f27eef-e3c3-493e-9d8e-85936a0c7ccf.png)
![advision](https://user-images.githubusercontent.com/87877685/161383221-aaf27d32-fe2d-4c99-b35f-fa437a8828c5.png)
![amigacdtv](https://user-images.githubusercontent.com/87877685/161383223-4883e1ef-dc8f-42fa-9bfd-97b095a3455b.png)
![apfm1000](https://user-images.githubusercontent.com/87877685/161383225-6b4f7a40-bbb1-4985-a388-719d7b841b5e.png)
![astrocade](https://user-images.githubusercontent.com/87877685/161383226-2738cb16-f1f8-45b4-93b4-c0dc1cc01989.png)
![bbcmicro](https://user-images.githubusercontent.com/87877685/161383227-4e1872d8-8ddb-4b62-b85c-eed16371f71c.png)
![cave3rd](https://user-images.githubusercontent.com/87877685/161383229-98ef7c0a-6a52-4a19-bc43-caf936a428d2.png)
![cdi](https://user-images.githubusercontent.com/87877685/161383230-ae018b6c-7b4f-4d54-9c62-12fc5d1edde7.png)
![coco](https://user-images.githubusercontent.com/87877685/161383231-949e9aaa-5042-419a-b5a9-740763edf758.png)
![cplus4](https://user-images.githubusercontent.com/87877685/161383233-56056827-8956-4785-9134-7bca6fb74fa5.png)
![creativision](https://user-images.githubusercontent.com/87877685/161383235-12f27aa8-5ffd-488e-965b-083aa09b2387.png)
![fm7](https://user-images.githubusercontent.com/87877685/161383237-ee317fcf-325c-4fa5-ae9d-1789b22238f7.png)
![gaelco](https://user-images.githubusercontent.com/87877685/161383238-240ad177-7307-4fe7-8289-c63dc14648c7.png)
![gamate](https://user-images.githubusercontent.com/87877685/161383239-68e02adf-57ca-4d31-a610-4c1c836a4f33.png)
![gamecom](https://user-images.githubusercontent.com/87877685/161383242-105a96a1-c42c-488d-a970-c5152e009948.png)
![gamepock](https://user-images.githubusercontent.com/87877685/161383244-acd95247-615b-4fd9-9230-1bb4ece7f8cb.png)
![gmaster](https://user-images.githubusercontent.com/87877685/161383245-e270d4cf-b663-440f-b8aa-cd7369142666.png)
![hikaru](https://user-images.githubusercontent.com/87877685/161383246-aace4c3c-4b5c-4a07-9811-99b98816c116.png)
![megaduck](https://user-images.githubusercontent.com/87877685/161383247-7e69fd60-3695-4b11-b885-7b667cf64add.png)
![n64dd](https://user-images.githubusercontent.com/87877685/161383249-627cf98b-6e54-4793-aa96-fc93ef6ae1b5.png)
![naomi2](https://user-images.githubusercontent.com/87877685/161383250-adb658c0-d51d-4a70-8e3d-54be42bcc267.png)
![pc88](https://user-images.githubusercontent.com/87877685/161383251-0067bde3-e289-4a13-b029-32771c8bec9a.png)
![pc98](https://user-images.githubusercontent.com/87877685/161383252-f2790642-7056-432a-a698-780613d8c2b9.png)
![pet](https://user-images.githubusercontent.com/87877685/161383256-d891f221-ddfa-409a-b1a7-1c667078525a.png)
![plugnplay](https://user-images.githubusercontent.com/87877685/161383258-eea1c4cf-08bc-4f16-aabd-df4b04fbacde.png)
![pv1000](https://user-images.githubusercontent.com/87877685/161383259-a9d81ba2-7066-4914-be61-50912cd7dafb.png)
![samcoupe](https://user-images.githubusercontent.com/87877685/161383261-eb56074b-5a15-4ca5-8883-d3e58fa9d69b.png)
![supervision](https://user-images.githubusercontent.com/87877685/161383263-25eee426-4019-4d89-bbff-6ceaf6aabc3b.png)
![thomson](https://user-images.githubusercontent.com/87877685/161383264-cb025ec6-db8a-4fde-9d76-eb5c526cf49f.png)
![ti99](https://user-images.githubusercontent.com/87877685/161383265-538e4568-1ce3-40fd-b561-626d3b46d345.png)
![tutor](https://user-images.githubusercontent.com/87877685/161383266-ef620d62-1b00-47c3-af45-b669e01442b5.png)
![arcadia](https://user-images.githubusercontent.com/87877685/161383294-2cf668c6-080d-497f-bfda-5c51183ac0d4.png)
![apfm1000](https://user-images.githubusercontent.com/87877685/161383298-1f877373-7ee4-45d2-ab31-75b920993839.png)
![cplus4](https://user-images.githubusercontent.com/87877685/161383321-00ef07a5-713c-444d-8f26-e2061559d46b.png)

2022-04-02 13:03 UTC, CkauNui commented
**g-spawnPL**, very nice, if u can please send PSD too or make it for dark theme

2022-04-02 13:08 UTC, Lendersmark commented
@g-spawnPL wow this is awesome!

2022-04-02 16:15 UTC, mathsensey commented
hello, will we have the chance to see Mugen one day? your work is amazing

2022-04-02 21:41 UTC, CkauNui commented
**g-spawnPL**, and please sent image in zip, current i no see name in image (161383298-1f877373-7ee4-45d2-ab31-75b920993839.png etc)

2022-04-03 05:59 UTC, g-spawnPL commented
> @g-spawnPL wow this is awesome!

thank you but this template is awsome not me :)

2022-04-03 06:01 UTC, g-spawnPL commented
> **g-spawnPL**, and please sent image in zip, current i no see name in image (161383298-1f877373-7ee4-45d2-ab31-75b920993839.png etc)

well I just tried to add it in the zip but github won't accept it, you have the names in the zipped layouts - both files must have the same one :)

2022-04-03 06:16 UTC, g-spawnPL commented
> **g-spawnPL**, very nice, if u can please send PSD too or make it for dark theme
[gimp_xcf.zip](https://github.com/CkauNui/ckau-book/files/8403919/gimp_xcf.zip)

I was honestly doing for my own purposes and didn't save everything. I use GIMP to edit the attached templates that I found on my PC

2022-04-03 06:26 UTC, g-spawnPL commented
if you like it, I'll share the rest of my graphics to this brilliant template when I'm done

I found some more:
[new.zip](https://github.com/CkauNui/ckau-book/files/8403931/new.zip)

2022-04-03 07:01 UTC, mathsensey commented
It's possible to add the MUGEN system ? 
Ckau Book is my favorite theme

2022-04-03 07:48 UTC, CkauNui commented
**mathsensey**, later

2022-04-03 08:21 UTC, CkauNui commented
**g-spawnPL**, mb try use photoshop for best transpency. And i can send psd template for u,
![image](https://user-images.githubusercontent.com/32091297/161418760-20bb776a-aaec-4a3c-89a5-4f9a6258a867.png)
![image](https://user-images.githubusercontent.com/32091297/161418785-c933c0a8-3fe4-4273-aade-105a92fd99e6.png)

2022-04-03 09:02 UTC, g-spawnPL commented
> **g-spawnPL**, mb try use photoshop for best transpency. And i can send psd template for u, ![image](https://user-images.githubusercontent.com/32091297/161418760-20bb776a-aaec-4a3c-89a5-4f9a6258a867.png) ![image](https://user-images.githubusercontent.com/32091297/161418785-c933c0a8-3fe4-4273-aade-105a92fd99e6.png)

as I wrote I don't know how to create graphics and that's why sometimes it doesn't look the best :) maybe someone from the community could take care of it

2022-04-03 09:04 UTC, g-spawnPL commented
> It's possible to add the MUGEN system ? Ckau Book is my favorite theme

I created today for MUGEN and sonicretro, maybe someone will find it usefu
[mugen.zip](https://github.com/CkauNui/ckau-book/files/8404133/mugen.zip)
[sonicretro.zip](https://github.com/CkauNui/ckau-book/files/8404134/sonicretro.zip)
l

2022-04-08 23:00 UTC, g-spawnPL commented
Hi
I am uploading the next systems for Batocera V34 with Polish and English translations :-)

[xegs.zip](https://github.com/CkauNui/ckau-book/files/8455706/xegs.zip)
[camplynx.zip](https://github.com/CkauNui/ckau-book/files/8455707/camplynx.zip)
[electron.zip](https://github.com/CkauNui/ckau-book/files/8455708/electron.zip)
[socrates.zip](https://github.com/CkauNui/ckau-book/files/8455709/socrates.zip)
[supracan.zip](https://github.com/CkauNui/ckau-book/files/8455710/supracan.zip)
[vsmile.zip](https://github.com/CkauNui/ckau-book/files/8455711/vsmile.zip)

preview:
![xegs](https://user-images.githubusercontent.com/87877685/162544432-4b4f33ed-18e1-46f8-a54d-299d63482b82.png)
![camplynx](https://user-images.githubusercontent.com/87877685/162544446-c9b2fb61-ae78-4de5-a7c2-d2cf12e98af7.png)
![electron](https://user-images.githubusercontent.com/87877685/162544463-901c3930-0071-437f-9231-9a54da4b1de6.png)
![socrates](https://user-images.githubusercontent.com/87877685/162544479-7d8430d3-844f-48cf-8f78-640a5727da88.png)
![supracan](https://user-images.githubusercontent.com/87877685/162544485-25bff26d-c518-4d3b-916d-0d4bc99c1639.png)
![vsmile](https://user-images.githubusercontent.com/87877685/162544499-a8ae7d51-70bb-4e16-a778-e04185a2cdd0.png)

2022-04-09 18:19 UTC, g-spawnPL commented
Hi
... next systems for Batocera V34 with Polish and English translations :-)

[archimedes.zip](https://github.com/CkauNui/ckau-book/files/8457538/archimedes.zip)
[atom.zip](https://github.com/CkauNui/ckau-book/files/8457539/atom.zip)

preview:
![archimedes](https://user-images.githubusercontent.com/87877685/162586715-a9d94b89-ef39-4930-aef9-63353e759f92.png)
![atom](https://user-images.githubusercontent.com/87877685/162586727-925d2f93-ca1e-4290-9671-3940f8ba6d42.png)

2022-04-13 22:11 UTC, Lendersmark commented
Great work @g-spawnPL ! I've updated by fork with your contributions (branch named "colorful-add-systems").

2022-04-15 11:39 UTC, g-spawnPL commented
another missing system to the collection :-)

[msxturbor.zip](https://github.com/CkauNui/ckau-book/files/8495701/msxturbor.zip)

preview:
![msxturbor](https://user-images.githubusercontent.com/87877685/163566496-702d052d-d600-4d35-a363-29f4d4cd79ae.png)

2022-04-18 19:57 UTC, g-spawnPL commented on _inc/layouts/Spectravideo.xml
> +			<text lang="pl">Descpriptions. Pls send me it in Discord</text>
pls add Polish translation:

```
SV-318 to podstawowy model z serii Spectravideo. Był wyposażony w klawiaturę typu chiclet, trudną w użyciu, obok której znajdowała się kombinacja kursora i joysticka. Jest to element w kształcie dysku z otworem w środku; po włożeniu czerwonego plastikowego "patyczka" w otwór jest to wbudowany joystick, po wyjęciu patyczka jest to strzałka kierunkowa do edytowania tekstu itp. Maszyna ta miała również tylko 16 KB pamięci RAM użytkownika (plus dodatkowe 16 KB pamięci RAM wideo), co ograniczało jej użyteczność, choć można ją było rozszerzyć za pomocą zewnętrznego modułu peryferyjnego.

Maszyna ta jest w zasadzie identyczna jak jej starszy brat SV-328, a jedyne różnice dotyczą klawiatury i ilości pamięci. ROM, możliwości rozbudowy, płyta główna i obudowa obu maszyn były identyczne.

Odniesienia do systemu operacyjnego Microsoft Extended BASIC nie należy mylić z MSX BASIC, chociaż niektórzy ówcześni marketingowcy twierdzili, że Microsoft Extended jest tym, co oznaczało MSX. SV-318 nie jest w pełni zgodny ze standardem MSX.
```

2022-04-18 20:07 UTC, g-spawnPL requested changes
Please resize the logo file so that its scale matches the templat
![archimedes](https://user-images.githubusercontent.com/87877685/163869491-2b2fec96-7a42-4509-9dd5-992072af84dc.png)
![atom](https://user-images.githubusercontent.com/87877685/163869565-f404ecc6-d0f6-47c5-9788-8e4b28bd9fa6.png)
![electron](https://
![socrates](https://user-images.githubusercontent.com/87877685/163869824-88d429c2-e9c1-4af8-a1de-66a7aa8d63c1.png)
user-images.githubusercontent.com/87877685/163869650-da0e19b1-1509-4a82-a4e4-ee0d3a040f68.png)

2022-04-19 17:44 UTC, Lendersmark commented on _inc/layouts/Spectravideo.xml
> +			<text lang="pl">Descpriptions. Pls send me it in Discord</text>
Thank you, translation added. If you notice some missing translations, please send them to me so I can update them.
(see "colorful-add-systems" branch in my repository: https://github.com/Lendersmark/ckau-book-enhanced/tree/colorful-add-systems )

2022-04-19 17:51 UTC, Lendersmark commented
> Please resize the logo file so that its scale matches the template:

The logos you posted seem pretty identical to the ones in the theme. But I don't have these systems in my installation so I can't test them :/ could you please send me screenshots? (better in private message so we don't flood this tread - or open an issue in my repo https://github.com/Lendersmark/ckau-book-enhanced/issues )

2022-04-27 21:50 UTC, Lendersmark commented
I'm going to close this pull request.
All changes have been merged to the master branch of my repo; another pull request has recently been made by @g-spawnPL which is basically identical to this one so let's keep that one and close this old one.

2022-04-27 21:50 UTC, closed without merging